### ISSUE TITLE
RAMI Enclosure

### ISSUE THREAD

**Issue by Mechsmith** [uwasystemhealth/RAMI#3]
Consists of:
- Decide on final design
- Draw design in Autodesk Inventor
- 3D print prototype
- Iterate to meet IP rating (>IP65 ideal)

**Comment by Mechsmith** [comment]
Rough print and CAD drawing of first iteration complete. Lid needs drawing and gasket channel needs significant improvement.

**Comment by Mechsmith** [comment]
The decision was made to go ahead and create the RAMI enclosure for the existing RAMI board. Once the RAMI v2 is complete, a separate enclosure can be made for that too.

Current enclosure has the body complete, but gasket channel still needs work. Lid and screw holes still need to be created.

**Comment by Mechsmith** [comment]
Gasket channel is complete, but needs sizing to be matched to an off-the-shelf O-ring. Lid and screw holes still need to be completed (equivalent gasket channel needs to be sized on the lid too).

**Comment by mhodki** [comment]
Update by Teams from Patrick today
Update on the RAMI is that I have found an o-ring supplier in Kwinana, but it is unclear exactly what sizes they have, so I'm going to need to drive down and have a look. I did an IP test using some DIY gasket, but faced a problem with the print de-laminating when I screwed the lid on. Next steps are to go to Kwinana to have a look and print out the new version of the enclosure with modified screw holes (drawing is already made).

**Comment by Mechsmith** [comment]
Found an O-ring from Transeals in Welshpool. Slightly too large for the groove, so modifying drawing and re-printing.

**Comment by Mechsmith** [comment]
Attempted to modify closure design to accommodate the O-ring, however printing it in ABS keeps failing so we need to order more PLA to complete the print (the O-ring groove should be the correct size in the updated CAD drawing).

**Comment by mhodki** [comment]
@Mechsmith  - remind me again if you will be using RAMI for your thesis.

**Comment by Mechsmith** [comment]
@mhodki Yes, if we can get some RAMIs operational they will be a good test case in my thesis.

**Comment by mhodki** [comment]
Closing this project and now being worked on as part of Patrick's thesis
